language: ruby

branches:
  only:
    - master
    - travis

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - jruby-1.7
  - rbx-2

env:
  matrix:
    - HANDLER="nokogiri"
    - HANDLER="ox"

matrix:
  exclude:
    - env: HANDLER="ox"
      rvm: jruby-19mode
    - env: HANDLER="ox"
      rvm: jruby-1.7
